//
//  GeofenceWireframe.swift
//  Cohesion
//
//  Created by Santi D on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class GeofenceWireframe: BaseWireframe<GeofenceViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = GeofenceViewController()
        super.init(viewController: moduleViewController)

        let interactor = GeofenceInteractor()
        let presenter = GeofencePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension GeofenceWireframe: GeofenceWireframeInterface {
}
