//
//  GeofenceInteractor.swift
//  Cohesion
//
//  Created by Santi D on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import CoreData
import Foundation

final class GeofenceInteractor {
}

// MARK: - Extensions -

extension GeofenceInteractor: GeofenceInteractorInterface {
    func saveCoordinates(longitude: Double, latitude: Double, completion: (String?) -> Void) {
        let context = CoreDataManager.context
        
        guard let entity = NSEntityDescription.entity(forEntityName: "Coordinates", in: context) else { return }
        
        let newCoordinate = NSManagedObject(entity: entity, insertInto: context)
        
        newCoordinate.setValue(longitude, forKey: "longitude")
        newCoordinate.setValue(latitude, forKey: "latitude")

        do {
            try context.save()
            completion(nil)
        } catch {
            completion("An error has ocurred!")
        }
    }
    
}
