//
//  GeofenceViewController.swift
//  Cohesion
//
//  Created by Santi D on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class GeofenceViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: GeofencePresenterInterface!
    
    var message = UILabel()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupUI()
        presenter.requestLocationAccess()
        presenter.startMonitoring()
    }
    
    deinit {
        presenter.stopMonitoring()
    }
    
    private func setupUI() {
        // UI
        view.backgroundColor = .gray
        message.numberOfLines = 0
        message.textAlignment = .center
        
        
        // Constraints
        view.addSubview(message)
        message.translatesAutoresizingMaskIntoConstraints = false
        message.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        message.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        
        message.topAnchor.constraint(equalTo: view.topAnchor, constant: 100).isActive = true
        message.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -100).isActive = true
    }
}

// MARK: - Extensions -

extension GeofenceViewController: GeofenceViewInterface {
    func updateMessageOnScreen(with text: String) {
        message.text = text
    }
    
    func userIsOnGeofence() {
        view.backgroundColor = .green
        
        updateMessageOnScreen(with: "Congratulations")
    }
    
    func userIsNotOnGeofence() {
        view.backgroundColor = .blue
        
        updateMessageOnScreen(with: "... thinking ...")
    }
}
