//
//  GeofenceInterfaces.swift
//  Cohesion
//
//  Created by Santi D on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol GeofenceWireframeInterface: WireframeInterface {
}

protocol GeofenceViewInterface: ViewInterface {
    func updateMessageOnScreen(with text: String)
    func userIsOnGeofence()
    func userIsNotOnGeofence()
}

protocol GeofencePresenterInterface: PresenterInterface {
    func requestLocationAccess()
    func startMonitoring()
    func stopMonitoring()
}

protocol GeofenceInteractorInterface: InteractorInterface {
    func saveCoordinates(longitude: Double, latitude: Double, completion: (String?) -> Void)
}
